name: Device support
description: Does your device work well with the integration? Please, tell it, so other users will know what to expect.
title: "[Device support] "
labels: ["documentation"]
assignees:
  - vaskivskyi
body:
  - type: markdown
    attributes:
      value: >
        Please, only submit device support using this form. If you would like to report a bug, use the [bug report](https://github.com/Vaskivskyi/ha-chroma/issues/new/choose) form.
        To submit a feature request, use the [feature request](https://github.com/Vaskivskyi/ha-chroma/issues/new/choose) form.
  - type: textarea
    attributes:
      label: Anything you want to mention?
      description: >
        Use this field for a short description if you would like.
  - type: markdown
    attributes:
      value: >
        # Environment and device
  - type: input
    id: device
    validations:
      required: true
    attributes:
      label: Your device model
      description: >
        Please, put in the full model of your device (or model unique code).
      placeholder: BlackWidow V3 Pro
  - type: input
    id: firmware_version
    validations:
      required: false
    attributes:
      label: Firmware version
      description: >
        Please, provide the full version of the ChromaSDK, as shown in HA, e.g. `3.28.01`
      placeholder: 3.28.01


