name: Feature request
description: Do you want a new feature for Chroma integration?
title: "[Feature] "
labels: ["enhancement"]
assignees:
  - vaskivskyi
body:
  - type: markdown
    attributes:
      value: >
        Please, only submit feature requests using this form. If you would like to report a bug, use the [bug report](https://github.com/Vaskivskyi/ha-chroma/issues/new/choose) form.
        To report that some device(s) work well, use the [device support](https://github.com/Vaskivskyi/ha-chroma/issues/new/choose) form.
  - type: textarea
    validations:
      required: true
    attributes:
      label: The idea
      description: >
        Please, describe your idea. The more details you provide, the easier it would be to understand it.

        How would this be useful?
  - type: markdown
    attributes:
      value: >
        # Environment and device
  - type: dropdown
    id: device
    attributes:
      label: Specific device(s)?
      description: >
        Is this feature only for some specific device(s)?
      options:
        - "No"
        - "Yes"
