name: Build

on:
  push:
    branches:
      - main
      - dev
  pull_request: ~
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  hacs:
    if: |
      github.event.pull_request.label.name != 'documentation' &&
      github.event.pull_request.label.name != 'github'
    name: HACS
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: HACS
        uses: "hacs/action@main"
        with:
          category: "integration"

  hassfest:
    if: |
      github.event.pull_request.label.name != 'documentation' &&
      github.event.pull_request.label.name != 'github'
    name: hassfest
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "home-assistant/actions/hassfest@master"
